[tools]
rojo = {source = "rojo-rbx/rojo", version = "=7.2.1"}
selene = {source = "Kampfkarren/selene", version = "=0.22.0"}
remodel = {source = "rojo-rbx/remodel", version = "=0.11.0"}
mantle = {source = "blake-mealey/mantle", version = "=0.11.3"}